NAD-1081 docs(card): add design reference tab
vtex/admin-ui pull request #138
Opened 2022-04-13 10:47 UTC by kevinch

#### What is the purpose of this pull request?
Update Card docs

#### What problem is this solving?
Lack of design content tab.

#### How should this be manually tested?
See link below.

#### Screenshots or example usage
n/a

#### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Quality improvement (tests or refactors)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Trivial change (small fix or feature that doesn't impact functionalities)
- [ ] Requires change to documentation, which has been updated accordingly

2022-04-13 11:38 UTC, davicostalf requested changes
The name of the tabs should be Code and Design, and Code should come first.

2022-04-13 17:03 UTC, kevinch commented
> The name of the tabs should be Code and Design, and Code should come first.

Will be updated once https://github.com/vtex/admin-ui/pull/131 is merged/rebased.

2022-04-13 17:21 UTC, Lenderson approved these changes

2022-04-14 20:28 UTC, davicostalf approved these changes
LGTM

2022-04-18 18:25 UTC, merged