NAD-1093 docs(textarea): add design ref tab
vtex/admin-ui pull request #148
Opened 2022-04-14 12:51 UTC by kevinch

#### What is the purpose of this pull request?
Add design ref tab.

#### What problem is this solving?
Lack of content.

#### How should this be manually tested?
See links below.

#### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Quality improvement (tests or refactors)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Trivial change (small fix or feature that doesn't impact functionalities)
- [ ] Requires change to documentation, which has been updated accordingly

2022-04-14 13:32 UTC, davicostalf requested changes

2022-04-14 13:32 UTC, davicostalf commented on packages/admin-ui-docs/docs/guidelines/components/text-area.mdx
> +4. Do use the required/optional flags when necessary, but prefer using one or another. 5. Add data validation to indicate when data hasn’t been inputted correctly.
Missing a line break

2022-04-14 13:32 UTC, davicostalf commented on packages/admin-ui-docs/docs/guidelines/components/text-area.mdx
> +2. If extra context is needed to clarify to the user where, or how the text inputted will appear, add a tooltip.
Please remove this second point

2022-04-18 22:01 UTC, marcelovicentegc commented on packages/admin-ui-docs/docs/guidelines/components/text-area.mdx
> +4. Do use the required/optional flags when necessary, but prefer using one or another. 5. Add data validation to indicate when data hasn’t been inputted correctly.
Done

2022-04-18 22:01 UTC, marcelovicentegc commented on packages/admin-ui-docs/docs/guidelines/components/text-area.mdx
> +2. If extra context is needed to clarify to the user where, or how the text inputted will appear, add a tooltip.
Done

2022-04-18 22:08 UTC, marcelovicentegc approved these changes

2022-04-18 22:09 UTC, merged