NAD-1088 Feature/radio design ref
vtex/admin-ui pull request #156
Opened 2022-04-14 17:26 UTC by kevinch

#### What is the purpose of this pull request?
Add design reference tab content.

#### What problem is this solving?
Lack of content.

#### How should this be manually tested?
See links below.

#### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Quality improvement (tests or refactors)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Trivial change (small fix or feature that doesn't impact functionalities)
- [ ] Requires change to documentation, which has been updated accordingly

2022-04-14 17:51 UTC, davicostalf requested changes

2022-04-14 17:51 UTC, davicostalf commented on packages/admin-ui-docs/docs/guidelines/components/radio.mdx
> +1. Use them for multiple choice options.
instead of "multiple" it should say "single"

2022-04-14 17:51 UTC, davicostalf commented on packages/admin-ui-docs/docs/guidelines/components/radio.mdx
> +3. Keep the list of options short. More than 6 options might start looking weird.
Change the last sentence to "For more than 6 options you should use a Select."

2022-04-14 17:51 UTC, davicostalf commented on packages/admin-ui-docs/docs/guidelines/components/radio.mdx
> +   7, Consider adding an "Other" option if needed, together with a Text Input to capture the user’s needs.
missing line break

2022-04-18 13:45 UTC, lucasaarcoverde commented
Duplicated #137

2022-04-18 13:45 UTC, lucasaarcoverde commented
Duplicated #137

2022-04-18 13:45 UTC, closed without merging