docs: review checkbox.mdx
vtex/admin-ui pull request #394
Opened 2022-09-02 11:59 UTC by julia-rabello

#### What is the purpose of this pull request?
Reviewing **Checkbox** component documentation and adding design guidelines.

There are two details I would like some help correcting (as illustrated in the gif below):
- Indentation of bullet points inside the collapsible content.
- Changing this collapsible background color to white instead of light blue, as validated [here](https://vtex.slack.com/archives/C01KE2JBL5P/p1662118967488599?thread_ts=1661886230.056799&cid=C01KE2JBL5P) with Davis.

Please let me know if there's something I can do to fix that directly in mdx or if I should open an issue in the repository 😄 

![collapsible-docs](https://user-images.githubusercontent.com/77292838/188136771-41d72441-cbc7-466a-8c24-68d9ebfba733.gif)

#### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Quality improvement (tests or refactors)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Trivial change (small fix or feature that doesn't impact functionalities)
- [x] Requires change to documentation, which has been updated accordingly

#### How does this PR make you feel? [:link:](http://giphy.com/)

2022-09-02 18:40 UTC, davicostalf requested changes
Os pontos que discutimos

2022-09-02 18:40 UTC, davicostalf commented on packages/admin-ui-docs/docs/components/checkbox.mdx
> +    <li>Use the Checkbox component to provide binary options, such as yes or no choices, where checking the Checkbox means yes and not checking it means no. Never use a radio component in this scenar
Esses dois primeiros pontos podem ser removidos, já estão atendidos pela descrição no overview.

2022-09-02 18:40 UTC, davicostalf commented on packages/admin-ui-docs/docs/components/checkbox.mdx
> +<details><summary>When to use the Radio, Switch, or Combobox Multiple components instead of the Checkbox component?</summary>
Acho que a ordem aqui na pergunta e nas respostas deveria ser: Switch, Radio, Combobox Multiple

2022-09-02 18:40 UTC, davicostalf commented on packages/admin-ui-docs/docs/components/checkbox.mdx
> +    <li>Choose the Radio component if only one option can be selected at a time.</li>
Choose the Radio component if only one option can be selected at a time and there are up to five options.

2022-09-02 18:40 UTC, davicostalf commented on packages/admin-ui-docs/docs/components/checkbox.mdx
> +  <ul>
Adicionar esse ponto:
Don't write labels that vary a lot in length between options.

2022-09-02 18:40 UTC, davicostalf commented on packages/admin-ui-docs/docs/components/checkbox.mdx
> +<details><summary>What should be the default state of a Checkbox?</summary>
What should be the default value of a Checkbox?

2022-09-02 18:40 UTC, davicostalf commented on packages/admin-ui-docs/docs/components/checkbox.mdx
> +When a Checkbox serves as confirmation, leave it unchecked by default and make it required to direct the attention of merchants. For example, the choice to accept terms and conditions.
Substituir essa resposta pela resposta que definimos pro Radio.

2022-09-02 18:40 UTC, davicostalf commented on packages/admin-ui-docs/docs/components/checkbox.mdx
> +Checkboxes allow merchants to make multiple independent choices in a form where there are at most five options and each option is binary.
Checkbox controls allow...

2022-09-08 16:10 UTC, davicostalf commented on packages/admin-ui-docs/docs/components/checkbox.mdx
> +    <li>Choose the Combobox Multiple component if multiple options can be selected and there are more than 5 available options.</li>
"5" should be written as "five"

2022-09-08 16:14 UTC, davicostalf commented on packages/admin-ui-docs/docs/components/checkbox.mdx
> +<details><summary>What should be the default value of a Checkbox?</summary>
Atualizar a resposta com base nos comentários na doc do Radio

2022-09-08 16:24 UTC, davicostalf commented on packages/admin-ui-docs/docs/components/checkbox.mdx
> +<details><summary>When to use a vertical or a horizontal Checkbox Group?</summary>
Atualizar a resposta com base nos comentários na doc do Radio

2022-09-09 21:27 UTC, davicostalf commented on packages/admin-ui-docs/docs/components/checkbox.mdx
> +  What to avoid:
<li>Don't include links. Use an alert component if this is necessary.</li>
    <li>Don't write more than one sentence.</li>
    <li>Don't use periods or commas.</li>

2022-09-09 21:29 UTC, davicostalf commented on packages/admin-ui-docs/docs/components/checkbox.mdx
> +    <li>Don't write labels that vary a lot in length between options.</li>
Don't write Checkbox labels that vary a lot in length between options

2022-09-13 18:34 UTC, davicostalf requested changes

2022-09-13 18:34 UTC, davicostalf commented on packages/admin-ui-docs/docs/components/checkbox.mdx
> +    <li>Choose the Switch component if the action is instant and does not require confirmation. For example, use a switch in a product form to show a new form section only if the product has variants
Choose the Switch component if the action is instant and does not require confirmation. For example, use a Switch in a User Settings page for the option to <em>Activate notifications<em>.

2022-10-26 13:53 UTC, julia-rabello commented
Closing this PR and recreating changes in PR #429 without conflicts as recommended by @lucasaarcoverde.

2022-10-26 13:53 UTC, closed without merging