Space tokens
vtex/admin-ui pull request #431
Opened 2022-10-28 20:18 UTC by anitavincent

#### What is the purpose of this pull request?

#### What problem is this solving?

#### How should this be manually tested?

#### Screenshots or example usage

#### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Quality improvement (tests or refactors)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Trivial change (small fix or feature that doesn't impact functionalities)
- [ ] Requires change to documentation, which has been updated accordingly

#### How does this PR make you feel? [:link:](http://giphy.com/)

2022-10-31 18:29 UTC, matheusps approved these changes
LGTM, just run eslint/prettier to remove the `;`

2022-11-01 17:24 UTC, davicostalf commented on packages/admin-ui/src/toast/toast.style.ts
> +    right: '$space-10',
Should be $space-12

2022-11-01 18:28 UTC, davicostalf requested changes
Besides these comments, there were also some changes in the Table:

https://620e870c28c4ae003a705d42-fqgjawvmqr.chromatic.com/?path=/story/admin-ui-review-table--bulk

https://620e870c28c4ae003a705d42-yzrwkyzydm.chromatic.com/?path=/story/admin-ui-review-table--bulk

If you compare these two stories, and other Table stories, you can see that the space between columns changed. I don't know if this has to do with the component itself or only its stories.

2022-11-01 18:28 UTC, davicostalf commented on packages/admin-ui/src/alert/alert.style.ts
>  export const button = styleVariants({
In the alert component, when there's an action and the button to dismiss, the space between them should be 8px (0.5rem / $space-2). However, it's now 2px (margin-right in action) + 4px (margin-left in dismiss).

2022-11-01 18:28 UTC, davicostalf commented on packages/admin-ui/src/button/button.style.ts
> +      marginY: negative('$space-4'),
should be $space-3

2022-11-01 18:28 UTC, davicostalf commented on packages/admin-ui/src/button/button.style.ts
> +      marginX: negative('$space-5'),
should be $space-4

2022-11-01 18:28 UTC, davicostalf commented on packages/admin-ui/src/radio/radio-group.style.ts
> +        marginRight: '$space-5',
This value is correct, but there's an issue (maybe with the inline component) that's making the radio have 8px of margin before the circle.

2022-11-04 19:15 UTC, davicostalf approved these changes
Besides the issues with the Radio Group and Checkbox Group, that will be solved in a separate task, everything else LGTM.

2022-11-04 20:14 UTC, marcelovicentegc approved these changes

2022-11-07 14:22 UTC, merged